name: ml_pro
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - missingno
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - keras
  - cpuonly
  - pip
  - plotly
  - python=3.10.2
